name: Scheduled Commits at Specific Times

on:
  schedule:
    - cron: '0 20 * * *' # 8:00 PM UTC
    - cron: '0 8 * * *'  # 8:00 AM UTC
    - cron: '0 2 * * *'  # 2:00 AM UTC
    - cron: '0 23 * * *' # 11:00 PM UTC
  workflow_dispatch: # For manual triggering

jobs:
  scheduled-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"

      - name: Log Time and Commit
        run: |
          # Define the log file
          log_file="log.txt"
          
          # Record the current UTC time
          current_time=$(date +"%Y-%m-%d %H:%M:%S %Z")
          echo "Current UTC Time: $current_time" >> $log_file
          
          # Determine which schedule triggered the workflow
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            case "${{ github.event.schedule }}" in
              '0 20 * * *')
                echo "This commit was triggered for 8:00 PM UTC (5:30 AM IST)." >> $log_file
                ;;
              '0 8 * * *')
                echo "This commit was triggered for 8:00 AM UTC (1:30 PM IST)." >> $log_file
                ;;
              '0 2 * * *')
                echo "This commit was triggered for 2:00 AM UTC (7:30 AM IST)." >> $log_file
                ;;
              '0 23 * * *')
                echo "This commit was triggered for 11:00 PM UTC (4:30 AM IST)." >> $log_file
                ;;
              *)
                echo "Unknown schedule triggered this commit." >> $log_file
                ;;
            esac
          else
            echo "Triggered manually or by another event." >> $log_file
          fi
          
          # Add the log file to the Git repository
          git add $log_file
          
          # Commit and push if there are changes
          if [[ $(git status --porcelain) ]]; then
            git commit -m "Automated log update - $(date)"
            git push
          fi
